.TH "AVR_MAN" 1 "2014-01-02"
.SH NAME
avr-man - a man(1) replacement to access the avr-libc manual pages
.SH SYNOPSIS
\fB avr-man \fR [ \fIOPTION\fR ] \fIpage\fR
.SH DESCRIPTION
.B avr-man
is a wrapper script for \fBman\fR(1), displaying results for the specified \fIpage\fR from the manual pages shipped with the
.IR avr-libc
package.
.PP
\fIOPTION\fR parameters are passed to man.

.SH "SEE ALSO"
\fBman\fR(1)
